#############################################################################
# Makefile for building: Ants-demo
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? ??? 20 13:52:03 2013
# Project:  Ants.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile Ants.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc-4.8
CXX           = g++-4.8
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang -I. -I/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/include -I. -Igui -Ilogic -Imanager -I. -I. -F/usr/local/Cellar/qt/4.8.4/lib
LINK          = g++-4.8
LFLAGS        = -headerpad_max_install_names -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.4/lib -L/usr/local/Cellar/qt/4.8.4/lib -framework QtGui -L/usr/local/Cellar/qt/4.8.4/lib -F/usr/local/Cellar/qt/4.8.4/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		main_window.cpp \
		gui/AntWidget.cpp \
		gui/IAntGUI.cpp \
		gui/IAntGuiImpl.cpp \
		logic/IAntLogic.cpp \
		logic/IAntLogicImpl.cpp \
		manager/AntManager.cpp moc_main_window.cpp \
		moc_AntWidget.cpp
OBJECTS       = main.o \
		main_window.o \
		AntWidget.o \
		IAntGUI.o \
		IAntGuiImpl.o \
		IAntLogic.o \
		IAntLogicImpl.o \
		AntManager.o \
		moc_main_window.o \
		moc_AntWidget.o
DIST          = /usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf \
		Ants.pro
QMAKE_TARGET  = Ants-demo
DESTDIR       = 
TARGET        = Ants-demo

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainForm.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ants.pro  /usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Ants.pro
/usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Ants.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Ants-demo1.0.0 || $(MKDIR) .tmp/Ants-demo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Ants-demo1.0.0/ && $(COPY_FILE) --parents main_window.hpp gui/AntWidget.hpp gui/IAntGUI.hpp gui/IAntGuiImpl.hpp logic/IAntLogic.hpp logic/IAntLogicImpl.hpp manager/AntManager.hpp .tmp/Ants-demo1.0.0/ && $(COPY_FILE) --parents main.cpp main_window.cpp gui/AntWidget.cpp gui/IAntGUI.cpp gui/IAntGuiImpl.cpp logic/IAntLogic.cpp logic/IAntLogicImpl.cpp manager/AntManager.cpp .tmp/Ants-demo1.0.0/ && $(COPY_FILE) --parents MainForm.ui .tmp/Ants-demo1.0.0/ && (cd `dirname .tmp/Ants-demo1.0.0` && $(TAR) Ants-demo1.0.0.tar Ants-demo1.0.0 && $(COMPRESS) Ants-demo1.0.0.tar) && $(MOVE) `dirname .tmp/Ants-demo1.0.0`/Ants-demo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Ants-demo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_main_window.cpp moc_AntWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main_window.cpp moc_AntWidget.cpp
moc_main_window.cpp: ui_MainForm.h \
		manager/AntManager.hpp \
		gui/IAntGUI.hpp \
		logic/IAntLogic.hpp \
		gui/IAntGuiImpl.hpp \
		gui/AntWidget.hpp \
		main_window.hpp
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ main_window.hpp -o moc_main_window.cpp

moc_AntWidget.cpp: gui/IAntGUI.hpp \
		gui/AntWidget.hpp
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/AntWidget.hpp -o moc_AntWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_MainForm.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainForm.h
ui_MainForm.h: MainForm.ui
	/usr/local/Cellar/qt/4.8.4/bin/uic MainForm.ui -o ui_MainForm.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp main_window.hpp \
		ui_MainForm.h \
		manager/AntManager.hpp \
		gui/IAntGUI.hpp \
		logic/IAntLogic.hpp \
		gui/IAntGuiImpl.hpp \
		gui/AntWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

main_window.o: main_window.cpp main_window.hpp \
		ui_MainForm.h \
		manager/AntManager.hpp \
		gui/IAntGUI.hpp \
		logic/IAntLogic.hpp \
		gui/IAntGuiImpl.hpp \
		gui/AntWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o main_window.cpp

AntWidget.o: gui/AntWidget.cpp gui/AntWidget.hpp \
		gui/IAntGUI.hpp \
		gui/IAntGuiImpl.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AntWidget.o gui/AntWidget.cpp

IAntGUI.o: gui/IAntGUI.cpp gui/IAntGUI.hpp \
		gui/AntWidget.hpp \
		gui/IAntGuiImpl.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IAntGUI.o gui/IAntGUI.cpp

IAntGuiImpl.o: gui/IAntGuiImpl.cpp gui/IAntGuiImpl.hpp \
		gui/IAntGUI.hpp \
		gui/AntWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IAntGuiImpl.o gui/IAntGuiImpl.cpp

IAntLogic.o: logic/IAntLogic.cpp logic/IAntLogic.hpp \
		logic/IAntLogicImpl.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IAntLogic.o logic/IAntLogic.cpp

IAntLogicImpl.o: logic/IAntLogicImpl.cpp logic/IAntLogicImpl.hpp \
		logic/IAntLogic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IAntLogicImpl.o logic/IAntLogicImpl.cpp

AntManager.o: manager/AntManager.cpp manager/AntManager.hpp \
		gui/IAntGUI.hpp \
		logic/IAntLogic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AntManager.o manager/AntManager.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

moc_AntWidget.o: moc_AntWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AntWidget.o moc_AntWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

